# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'AspirePipelineVariables'
    

steps:
  - task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash

  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.
  
  - pwsh: |
      azd pipeline config --environment tf-aspire-autogen --provider azdo --principal-name $(principal-name) --principal-id $(principal-id)
    displayName: azd pipeline config in-pipeline

  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
        # azconnection is created by azd pipeline config
        azureSubscription: tf-aspire-sc
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          azd provision --no-prompt
          env:
    env:
        # azd build-in variables.
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        AZURE_ENV_NAME: $(AZURE_ENV_NAME)
        AZURE_LOCATION: $(AZURE_LOCATION)

  - task: AzureCLI@2
    displayName: Deploy Application
    inputs:
        azureSubscription: tf-aspire-sc
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          azd deploy --no-prompt
    env:
        # azd build-in variables.
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        AZURE_ENV_NAME: $(AZURE_ENV_NAME)
        AZURE_LOCATION: $(AZURE_LOCATION)